### ISSUE TITLE
Not able to build an app due to :react-native-apple-authentication:androidJavadoc Failure

### ISSUE THREAD

**Issue by BotanMan** [invertase/react-native-apple-authentication#313]
When I run `react-native run-android`

I get such errors
```
Note: .../node_modules/@invertase/react-native-apple-authentication/android/src/main/java/com/RNAppleAuthentication/AppleAuthenticationAndroidModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
....
  symbol:   class Callback
  location: class AppleAuthenticationModule
.../node_modules/react-native-apple-authentication/android/src/main/java/com/reactlibrary/AppleAuthenticationModule.java:22: error: cannot find symbol
    @ReactMethod
     ^
  symbol:   class ReactMethod
  location: class AppleAuthenticationModule
19 errors

> Task :react-native-apple-authentication:androidJavadoc FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-apple-authentication:androidJavadoc'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '.../node_modules/react-native-apple-authentication/android/build/tmp/androidJavadoc/javadoc.options'
```

RN: 63.5

openjdk version "15" 2020-09-15
OpenJDK Runtime Environment AdoptOpenJDK (build 15+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15+36, mixed mode, sharing)

Gradle 6.8

It doesn't happen when I do the bundle, strange, but I'm not able to develop on emulator anymore, it was working half of year ago when I was working on this project last time

**Comment by mikehardy** [comment]
Hi there - JDK11 is a supported JDK for react-native
RN 0.63 is so old it is out of support. General policy for react-native is to support a couple versions and that's it  - https://github.com/reactwg/react-native-releases/#releases-support-policy - we support a couple more but certainly not that far back.

In general logging issues on older versions is inefficient as it just turns up the same answer "Oh, that's not compatible, upgrade" or "Oh, we fixed that, upgrade"

So I encourage you to upgrade to current stable versions here and for react-native (https://react-native-community.github.io/upgrade-helper/) and open a new issue as needed

**Comment by BotanMan** [comment]
Thanks @mikehardy 

Tried with JDK 11, still having the same issue...

The issue for me is that it was working at summer, so I just need to rebuild the project and add a few fixes, while it seems I had to migrate it to do that, while migration would take hours or days as there are a lot of dependencies, fixes just minutes :D

Could you also provide other possible workaround I can check out? 
Best

**Comment by mikehardy** [comment]
The desire to defer maintenance as long as possible is indeed quite strong, I do understand.
I have no other workarounds I can think of though.

Please when you open issues in open source repositories do so on current stable versions as a general rule
